# Generated by Django 5.2.12 on 2026-08-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('proposal', 'Proposal Template'), ('srs', 'SRS / Requirements Template'), ('report', 'Final Report Template'), ('checklist', 'Defense / Evaluation Checklist'), ('guideline', 'General Guideline'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('external_link', models.URLField(blank=True)),
                ('department', models.CharField(blank=True, help_text='Leave blank to show to all departments', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_resource',
                'ordering': ['category', 'title'],
            },
        ),
    ]
