# Generated by Django 5.2.12 on 2026-05-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, choices=[('5', '<5 hrs/week'), ('5-10', '5–10 hrs/week'), ('10-20', '10–20 hrs/week'), ('20+', '20+ hrs/week')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('CS', 'CS'), ('DS', 'DS'), ('SE', 'SE'), ('EE', 'EE')], default='IT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('fyp', 'FYP Partner'), ('paid', 'Paid Task'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, choices=[('BSSE', 'BSSE'), ('BSCS', 'BSCS'), ('BSDS', 'BSDS'), ('BSIT', 'BSIT')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7')], null=True),
        ),
    ]
