# Generated by Django 6.1 on 2026-08-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_loginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='Uploaded CV/resume (PDF, DOCX or TXT)', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
