# Generated by Django 5.2.12 on 2026-08-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_options_remove_community_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypostlike',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like (Heart)'), ('sad', 'Sad'), ('laugh', 'Laughing'), ('dislike', 'Dislike')], default='like', max_length=10),
        ),
    ]
