# Generated by Django 5.2.12 on 2026-08-19 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('frameworks', 'Frameworks & Libraries'), ('ai_data', 'AI, Data Science & ML'), ('databases', 'Databases & Storage'), ('devops_cloud', 'DevOps & Cloud'), ('mobile', 'Mobile Development'), ('web_design', 'Web & UI/UX Design'), ('security_qa', 'Cybersecurity & QA'), ('others', 'Tools & Other Tech')], max_length=20)),
            ],
            options={
                'db_table': 'core_skill',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_email_verification',
            },
        ),
        migrations.CreateModel(
            name='LoginOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_login_otp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT'), ('CS', 'CS'), ('DS', 'DS'), ('SE', 'SE'), ('EE', 'EE')], default='IT', max_length=10, null=True)),
                ('program', models.CharField(blank=True, choices=[('BSSE', 'BSSE'), ('BSCS', 'BSCS'), ('BSDS', 'BSDS'), ('BSIT', 'BSIT')], max_length=10, null=True)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7')], null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('looking_for', models.CharField(blank=True, choices=[('fyp', 'FYP Partner'), ('paid', 'Paid Task'), ('both', 'Both')], max_length=10, null=True)),
                ('availability', models.CharField(blank=True, choices=[('5', '<5 hrs/week'), ('5-10', '5–10 hrs/week'), ('10-20', '10–20 hrs/week'), ('20+', '20+ hrs/week')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.CharField(blank=True, help_text='e.g. Fall 2022, Spring 2023', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='University email verified')),
                ('id_card', models.ImageField(blank=True, help_text='Student card photo for senior verification', null=True, upload_to='id_cards/')),
                ('is_id_verified', models.BooleanField(default=False, help_text='Reviewed and approved by an admin')),
                ('is_supervisor', models.BooleanField(default=False, help_text='Faculty / supervisor account that can endorse FYP posts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_profile',
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('skill', models.CharField(blank=True, max_length=100)),
                ('post_type', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_saved_search',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_userskill',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
