# Generated by Django 6.1 on 2026-08-20 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profile_resume_profile_resume_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.CharField(max_length=220)),
                ('icon', models.CharField(default='bi-people-fill', help_text='Bootstrap icon class, e.g. bi-code-slash', max_length=40)),
                ('color', models.CharField(default='#1B6FFF', help_text='Hex color for the community badge/icon', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_skills', models.ManyToManyField(blank=True, help_text='Skills that auto-qualify a student for this community', related_name='communities', to='accounts.skill')),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'db_table': 'community_community',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_membership',
                'ordering': ['-joined_at'],
                'unique_together': {('community', 'user')},
            },
        ),
    ]
